language: swift
osx_image: xcode9.2 #2
script:
  - xcodebuild -scheme POC-CI -project POC-CI/POC-CI.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
