language: objective-c  #1
osx_image: xcode9.2 #2
xcode_project: POC-CI.xcodeproj #3
xcode_scheme: POC-CI

script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.2 -project POC-CI.xcodeproj -scheme POC-CI CODE_SIGNING_REQUIRED=NO
